// Code generated by protoc-gen-go.
// source: command.proto
// DO NOT EDIT!

/*
Package connector is a generated protocol buffer package.

It is generated from these files:
	command.proto

It has these top-level messages:
	Inform
	Notification
	Empty
*/
package connector

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Inform struct {
	Node map[string]string `protobuf:"bytes,1,rep,name=Node" json:"Node,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Inform) Reset()                    { *m = Inform{} }
func (m *Inform) String() string            { return proto.CompactTextString(m) }
func (*Inform) ProtoMessage()               {}
func (*Inform) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Inform) GetNode() map[string]string {
	if m != nil {
		return m.Node
	}
	return nil
}

type Notification struct {
	Inform []*Inform `protobuf:"bytes,1,rep,name=Inform" json:"Inform,omitempty"`
}

func (m *Notification) Reset()                    { *m = Notification{} }
func (m *Notification) String() string            { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()               {}
func (*Notification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Notification) GetInform() []*Inform {
	if m != nil {
		return m.Inform
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Inform)(nil), "connector.Inform")
	proto.RegisterType((*Notification)(nil), "connector.Notification")
	proto.RegisterType((*Empty)(nil), "connector.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Notifier service

type NotifierClient interface {
	Notify(ctx context.Context, in *Notification, opts ...grpc.CallOption) (*Empty, error)
}

type notifierClient struct {
	cc *grpc.ClientConn
}

func NewNotifierClient(cc *grpc.ClientConn) NotifierClient {
	return &notifierClient{cc}
}

func (c *notifierClient) Notify(ctx context.Context, in *Notification, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/connector.Notifier/Notify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Notifier service

type NotifierServer interface {
	Notify(context.Context, *Notification) (*Empty, error)
}

func RegisterNotifierServer(s *grpc.Server, srv NotifierServer) {
	s.RegisterService(&_Notifier_serviceDesc, srv)
}

func _Notifier_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Notification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connector.Notifier/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).Notify(ctx, req.(*Notification))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connector.Notifier",
	HandlerType: (*NotifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _Notifier_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for Register service

type RegisterClient interface {
	Registe(ctx context.Context, in *Inform, opts ...grpc.CallOption) (*Empty, error)
}

type registerClient struct {
	cc *grpc.ClientConn
}

func NewRegisterClient(cc *grpc.ClientConn) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) Registe(ctx context.Context, in *Inform, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/connector.Register/Registe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Register service

type RegisterServer interface {
	Registe(context.Context, *Inform) (*Empty, error)
}

func RegisterRegisterServer(s *grpc.Server, srv RegisterServer) {
	s.RegisterService(&_Register_serviceDesc, srv)
}

func _Register_Registe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Inform)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).Registe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connector.Register/Registe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).Registe(ctx, req.(*Inform))
	}
	return interceptor(ctx, in, info, handler)
}

var _Register_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connector.Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registe",
			Handler:    _Register_Registe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0xce, 0xcf, 0xcb, 0x4b,
	0x4d, 0x2e, 0xc9, 0x2f, 0x52, 0x2a, 0xe2, 0x62, 0xf3, 0xcc, 0x4b, 0xcb, 0x2f, 0xca, 0x15, 0xd2,
	0xe7, 0x62, 0xf1, 0xcb, 0x4f, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x92, 0xd6, 0x83,
	0xab, 0xd1, 0x83, 0x28, 0xd0, 0x03, 0xc9, 0xba, 0xe6, 0x95, 0x14, 0x55, 0x06, 0x81, 0x15, 0x4a,
	0x99, 0x73, 0x71, 0xc2, 0x85, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x81, 0x9a, 0x19, 0x35,
	0x38, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26, 0xb0,
	0x18, 0x84, 0x63, 0xc5, 0x64, 0xc1, 0xa8, 0x64, 0xc9, 0xc5, 0xe3, 0x97, 0x5f, 0x92, 0x99, 0x96,
	0x99, 0x9c, 0x58, 0x92, 0x99, 0x9f, 0x27, 0xa4, 0x09, 0x73, 0x03, 0xd4, 0x6e, 0x41, 0x0c, 0xbb,
	0x83, 0xa0, 0x0a, 0x94, 0xd8, 0xb9, 0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x8d, 0x1c, 0xb9, 0x38,
	0x20, 0x66, 0xa4, 0x16, 0x09, 0x99, 0x72, 0xb1, 0x81, 0xd9, 0x95, 0x42, 0xe2, 0x48, 0x3a, 0x91,
	0xad, 0x90, 0x12, 0x40, 0x92, 0x00, 0x1b, 0xa0, 0xc4, 0x60, 0x64, 0xc3, 0xc5, 0x11, 0x94, 0x9a,
	0x9e, 0x59, 0x5c, 0x02, 0x34, 0xc2, 0x80, 0x8b, 0x1d, 0xca, 0x16, 0xc2, 0xb4, 0x1d, 0x9b, 0xee,
	0x24, 0x36, 0x70, 0x50, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xef, 0x39, 0x44, 0x5e, 0x5b,
	0x01, 0x00, 0x00,
}
